-- タスクテーブル作成（Oracle用）
CREATE TABLE tasks (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    status VARCHAR2(50) DEFAULT 'TODO' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- インデックス
CREATE INDEX idx_tasks_status ON tasks(status);
CREATE INDEX idx_tasks_created_at ON tasks(created_at);

-- コメント
COMMENT ON TABLE tasks IS 'タスク管理テーブル';
COMMENT ON COLUMN tasks.id IS 'タスクID（自動採番）';
COMMENT ON COLUMN tasks.title IS 'タスクタイトル';
COMMENT ON COLUMN tasks.description IS 'タスク詳細説明';
COMMENT ON COLUMN tasks.status IS 'タスクステータス（TODO/IN_PROGRESS/DONE）';
COMMENT ON COLUMN tasks.created_at IS '作成日時';
COMMENT ON COLUMN tasks.updated_at IS '更新日時';
